version: "3.8"

services:
  ####################################
  # Atomic Microservice: Accounts
  ####################################
  accounts:
    build:
      context: ./services/accounts
      dockerfile: Dockerfile
    env_file:
      - 'dev.env'
    ports:
      - "30000:5000"

  ####################################
  # Atomic Microservice: Events
  ####################################
  events:
    build:
      context: ./services/events
      dockerfile: Dockerfile
    env_file:
      - 'dev.env'
    ports:
      - "31000:5000"

  ####################################
  # Atomic Microservice: Transport
  ####################################
  transport:
    build:
      context: ./services/transport
      dockerfile: Dockerfile
    env_file:
      - 'dev.env'
    ports:
      - "32000:5000"